name: Go Lint

on:
  push:
  pull_request:

jobs:

  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install lame
      run: sudo apt-get install libmp3lame-dev

    - name: golangci-lint
      uses: golangci/golangci-lint-action@v2
      with:
        # Optional: version of golangci-lint to use in form of v1.2 or v1.2.3 or `latest` to use the latest version
        version: v1.29
